ktor:
  application:
    modules:
      - stapi.ApplicationKt.module
  deployment:
    port: 8888

jwt:
  secret : "secret"
  issuer : "http://127.0.0.0:8888/"
  audience : "http://127.0.0.0:8888/auth/users/me"
  realm : "Access to 'users' protected"

#  domain: "http://localhost:8888"
